### PR TITLE
Reorganizing repo and build scripts

### PR DESCRIPTION
**Pull request by assambar**
Read the README.md for more info on how the code is organized with this change.

- single script to build whatever you need - e.g. `./wl-make.sh php/php-7.3.33`
- patches stored separately so patch evolution history is accessible
- no dependency on other cloned repositories, submodules or pre-built libraries - all necessary code is cloned in a shallow way on-the-fly, then patched and then built

### CODE REVIEW

**Comment by Angelmmiguel** [comment]
LGTM! I really like the new organization. I believe it's clear and it helps to grow this repository. 

The only point I'm missing is where the target repository (ex. sqlite.git) changes it's HEAD to the specific version. I see the script that sets the repo is in the top level folder of libs and languages. However, I couldn't identify where the version is properly set before start building.

Apart from that, I would also include a clear list of tools required to build the different languages / libs. This may be done directly by documentation. For example, include a `Requisites` section on the `README.md` file on every language / lib version.

**Comment by assambar** [comment]
> LGTM! I really like the new organization. I believe it's clear and it helps to grow this repository.

Thanks @Angelmmiguel 

> The only point I'm missing is where the target repository (ex. sqlite.git) changes it's HEAD to the specific version. I see the script that sets the repo is in the top level folder of libs and languages. However, I couldn't identify where the version is properly set before start building.

The base tag for each version is checked out separately inside build-staging. So you'd have `build-staging/php/php-7.3.33/checkout` and then also `build-staging/php/php-7.4.32`. This is a shallow clone of the tag so it's usually pretty fast.
 
> Apart from that, I would also include a clear list of tools required to build the different languages / libs. This may be done directly by documentation. For example, include a `Requisites` section on the `README.md` file on every language / lib version.

You're right. I will add more information on this.

**Review by ereslibre — APPROVED** [review]
Thank you @assambar! LGTM. I tried to build php-7.3.33 on an ubuntu container and worked fine.

I added a couple of commits to the PR that apply small fixes.

**Comment by assambar** [comment]
This addresses https://github.com/vmware-labs/webassembly-language-runtimes/issues/4

**Pull request merged**
